export const fakeCourseData = [
  {
    _id: "1",
    imageUrl: "/images/image-1.webp",
    title: "Learning historical words and sentences",
    lessons: 10,
    students: 140,
    level: "Basic",
    completed: 5,
  },
  {
    _id: "2",
    imageUrl: "/images/image-1.webp",
    title: "Learning historical words and sentences",
    lessons: 3,
    students: 60,
    level: "Meduim",
    completed: 8,
  },
  {
    _id: "3",
    imageUrl: "/images/image-1.webp",
    title: "Learning historical words and sentences",
    lessons: 100,
    students: 1400,
    level: "Advanced",
    completed: 10,
  },
  {
    _id: "4",
    imageUrl: "/images/image-1.webp",
    title: "Learning historical words and sentences",
    lessons: 5,
    students: 40,
    level: "Basic",
    completed: 2,
  },
  {
    _id: "5",
    imageUrl: "/images/image-1.webp",
    title: "Learning historical words and sentences",
    lessons: 10,
    students: 140,
    level: "Basic",
    completed: 5.6,
  },
];
